### ISSUE TITLE
gb-vendor: add purge subcommand that removes imports that are not referenced from $PROJECT/src

### ISSUE THREAD

**Issue by davecheney** [constabulary/gb#135]
Closes constabulary/gb-vendor#7

**Comment by davidkaya** [comment]
Suggestion:
We could parse imports from $PROJECT/src with https://golang.org/pkg/go/ast/ into Set (`map[string]struct{}`?) and compare it with imports from manifest file and remove those which are not referenced?

**Comment by pires** [comment]
+1

**Comment by davidkaya** [comment]
Are imports from the project already parsed and saved somewhere or do I have to parse the imports from $root/src? I wasn't able to find anything related to that.

**Comment by davecheney** [comment]
This will be quite an involved feature as it requires loading all the source in `$PROJECT/src`, extacting the set of dependencies that are not met from the source iteslf; thus met from vendor/src/, then loading all the importpaths determinting packages references and unrefernced, then removing the unreferenced ones.

**Comment by davidkaya** [comment]
Can I rely on the fact that all the dependencies (referenced and unreferenced) will be in the Manifest file or is it also required to parse the {{vendor/*}} structure? 

I think I should be able to rely on that, because the {{purge}} command is sub-command of {{gb vendor}}, thus the dependencies should be in the Manifest file.

**Comment by davecheney** [comment]
yes, purge should only remove items mentioned in the manifest.
