### ISSUE TITLE
gb-vendor: fetch / update: vendor specific revision of a package 

### ISSUE THREAD

**Issue by davecheney** [constabulary/gb#136]
I was thinking that it would be nice if gb-vendor had additional arguments, where user would be able to specify commit/branch of a package he or she wants to vendor.

Something like gb-vendor -c 21dc14a51f github.com/user/sample or gb-vendor -b branch_name github.com/user/sample

**Comment by davecheney** [comment]
flags should be
`gb vendor $REPO --branch $branch --revision $revision`

**Comment by davidkaya** [comment]
@davecheney 
`--revision` this is commit sha?

**Comment by davecheney** [comment]
Yes. I feel strongly that go packages do not have versions (at the moment).

**Comment by pires** [comment]
I would vote for `tags` instead of `branches`.

**Comment by PSG-Luna** [comment]
I think having both makes sense

**Comment by rnapier** [comment]
Is a special argument needed to handle tags? For git, most "treeish" things are equivalent syntax, but that's not universal.

I assume still the actual SHA should be recorded. Will Manifest need to record how that SHA was selected (branch, SHA, tag)?

If you don't pass a branch, how does update work? Will it always update to master even if the original SHA was on a branch?

**Comment by drewwells** [comment]
Both would be handy, but sha is very nice for now

**Comment by davidkaya** [comment]
I have one suggestion. `gb vendor update $repo` should not have `--branch` or `--revision` tag, I think it should only require `$repo`, because the branch/revision are specified in the manifest. I think that `gb vendor update $repo` should only pull latest changes for the branch specified in the manifest file (revision is irrelevent, because after updating, there will be new revision).

On the other hand, if a user wants to switch branch/revision of the package, I would suggest new command `gb vendor rebase --branch $branch $repo` or `gb vendor rebase --revision $rev $repo`.

**Comment by davecheney** [comment]
Yup, that makes sense.

Instead of rebase, I'd prefer people do remove and then fetch.

Gb vendor is just a convenience wrapper around an action they could take
manually, so I'm not interested in addressing extreme cases.

**Comment by davidkaya** [comment]
Implemented in #132
