### ISSUE TITLE
gb help prints commands in random order

### ISSUE THREAD

**Issue by natefinch** [constabulary/gb#142]
...likely due to the commands being stored in a map and printed in map-order (i.e. random)

**Comment by davecheney** [comment]
Will fix, this is a stupid bug caused by my reinvention of the wheel.

**Comment by davidkaya** [comment]
What about adding "Name" into Command struct and using slice for storing?

**Comment by davecheney** [comment]
You can sort by map keys

for k, _ := range ... {
    s = append(s, k)
}

sort.Strings(s)

for _ v := range s {
      print(map[v])
}

or something

**Comment by davidkaya** [comment]
Well I found adding Name to the Command more intuitive, since you are registering a command by passing name and a specific command into `registerCommand(...)` which in the end is coupling name of the command with the command. 

Also you can get a Command by having it's name (from the map), but you can't get name of the command by having command, something like this:
* Name ---> Command (constant)
* Command -x-> Name (not possible)

If you add Name to the Command struct you will be able to register command just by passing the command which will have its name already set and this will hold;
* Name ---> Command (linear)
* Command ---> Name (constant)

**Comment by davecheney** [comment]
SGTM. The current registercommand is just a simple wrapper around the map
insertion. There is no reason it couldn't be written as

registerCommand(c *cmd.Command) {
    cpmmands[c.Name] = c
}
