### ISSUE TITLE
Vendor with specific tag / commit?

### ISSUE THREAD

**Issue by crsmithdev** [constabulary/gb#17]
Shouldn't `gb vendor` support a tag / commit option?  Otherwise it just does exactly the same thing as `go get`.

**Comment by davecheney** [comment]
Gb vendor is just a proof of concept at the moment, it just shells out to go get to help bootstrap your project. 

It would be nice to teach it about tags and versions, possibly so I can be used to update an existing vendored package. 

For the moment the work around is to fetch the source manually. 

+help wanted

**Comment by elithrar** [comment]
Are you open to the idea of gb being able to:

- Work for libraries? i.e. someone can fetch my library and all deps and
(should they wish to) use `gb build mylib` to use those deps instead of
what's on their global GOPATH?
- Store a reference to those tags in some kind of .vendordotfilething?
- etc?

I write more libraries than 'package mains' but being able to provide a
reproducible version  would be extremely useful. The workflow would
probably be `go get` (which should fetch the vendor/ path too) and then `gb
build` to build off ./vendor.

**Comment by davecheney** [comment]
Matt, can you please make a new issue for this. I want to address this
separately.

**Comment by andrewchambers** [comment]
Imo a plugin which tackles source packaging and library version compatibility via a package file might be cool. Something like cargo/leiningen/maven. We could also have a package server to go with the plugin.

**Comment by davecheney** [comment]
> We could also have a package server to go with the plugin.

That sounds much larger in scope than I imagined, but that's why it's
implemented as a plugin, _anyone_ can write a plugin, they don;t need to be
part of the main gb distribution.

**Comment by andrewchambers** [comment]
Yeah, I guess whoever wants to step up can just do it in their own plugin repo. If a plugin gets traction, it can get referenced from the official readme here.

**Comment by davecheney** [comment]
What I am planning on doing is moving `gb-vendor` to it's own repository so it can evolve independent of `gb`. This will happen when I've got the new github pages' site up with updated documentation. I'll close this then.

**Comment by davecheney** [comment]
`gb-vendor` has been moved to it's own repository, as discussed in #29
