### ISSUE TITLE
Please improve the output of gb test.

### ISSUE THREAD

**Issue by hyper-carrot** [constabulary/gb#216]
I used `gb test`, but only got 
```
testing: warning: no tests to run
PASS
testing: warning: no tests to run
PASS
```
I appended flag `-v`, but got the output too much. I want to get a  just enough output. It look like:
```
=== RUN TestGetJsApiTicketWithRetry-4
--- PASS: TestGetJsApiTicketWithRetry-4 (0.17s)
	jsapiticket_test.go:101: The JS API ticket: abc
=== RUN TestPushMessage-4
--- PASS: TestPushMessage-4 (0.40s)
	msgsender_test.go:99: The open ID number: 3
=== RUN TestMessagePushInfoToJson-4
--- PASS: TestMessagePushInfoToJson-4 (0.00s)
PASS
ok  	weixin/client	1.332s
```

**Comment by demizer** [comment]
The gb test command has command arguments for selecting two levels of logging output, debug and quiet. The output logging of gb uses log levels, ``-v`` sets the log level to DEBUG (the lowest level), but in this case, you should really be using ``-q`` which sets the log level to the default value of "INFO".

To the uninitiated, ``-q`` should make the tests produce no output at all (which is currently done by not passing any log level selection parameters), but since the upstream go test binary code does not use log levels, but uses ``-v`` to show output, this was done as a compromise.

**Comment by hyper-carrot** [comment]
@demizer Yes, It's for compatibility with go standard tool. It will make `gb` more friendly.

**Comment by rzendacott** [comment]
:+1: for this change.
