### ISSUE TITLE
`gb build` is actually `gb install`

### ISSUE THREAD

**Issue by calmh** [constabulary/gb#22]
I know of the persistent advice of "use go install" when "go build" doesn't do what people expect... But "go build" does what *I* expect, or in certain cases `GOBIN=something go install` does it better.

I was hoping that `gb build` would do the right thing (in my opinion) by placing the build artifact in the current directory, so that I can tar it up etc as part of a build process. However in actuality it ends up in `../../../../bin`, which is an annoying place to go looking for build artifacts.

**Comment by davecheney** [comment]
Sorry this is a design decision.

gb always works on projects, and all packages and binaries produced are scoped by a package, so they end up in $PROJECT/pkg and $PROJECT/bin respectively.

I also took the opportunity to return the build command to what every beginner gopher expected it to be ( and then we have to have the confusing chat that build builds and throws away, etc )

gb doesn't support GOBIN and this won't change in the future, but because gb works on projects, your binaries will always be in $PROJECT/bin.

**Comment by calmh** [comment]
Is the expectation that a repo should nowadays have a structure with a README, top level `src` directory, etc? I tried that, with a repo that is anyway under my $GOPATH, and there was unhappiness but I may have screwed up.

**Comment by davecheney** [comment]
i'd suggest making a new gb repo for your project

mkdir -p ~/projects/demo/src
cd ~/projects/demo

~/projects/demo is your $PROJECT

**Comment by calmh** [comment]
Yeah, I realized. For my existing project, which is `github.com/syncthing/syncthing`, that would mean a repo `syncthing` in `~/projects/syncthing` and that repo would then contain `src/github.com/syncthing/syncthing/cmd/syncthing` (etc) and the build command would be `gb build github.com/syncthing/syncthing/cmd/syncthing` which is somewhat cumbersome. Or is the intention that I move to a not "fully qualified" package name, as the repo is anyway no longer go-gettable?

**Comment by davecheney** [comment]
gb projecs are not "go gettable" so there is no requirement to maintain the full fdqn structure in your code. You can keep it for simplicity if you like, or you can restructure your code, something like this

~/projects/syncthing/src/cmd/syncthing

and so forth

**Comment by calmh** [comment]
Reasonable. I'll give it a try, and see what I can do about that plugin.
