### ISSUE TITLE
Question: Should `go vendor fetch` fail when it can't find the depset?

### ISSUE THREAD

**Issue by markmandel** [constabulary/gb#249]
Using `go vendor fetch` it now seems that `recurse` is now defaulted to true.

If the project doesn't have a depset (which looks to be a whole vendor/src dir, [from the code](https://github.com/constabulary/gb/blob/master/cmd/gb-vendor/fetch.go#L156-L159)), then `go vendor fetch` fails.

For example:

```bash
gb vendor fetch github.com/nu7hatch/gouuid
FATAL command "fetch" failed: unable to locate depset for "github.com/nu7hatch/gouuid"
FATAL command "vendor" failed: exit status 1
make: *** [deps] Error 1
```

Running the same command with `-no-recurse` works, but it seems strange that I have to specify this.

```bash
gb vendor fetch -no-recurse github.com/nu7hatch/gouuid
```

I would have thought that if the depsets simply don't exist, then it would be ignored, as there was no recursion to be done. I can't imaging there are many Go projects out there right now that have a full vendor/src directory, so I'm wondering if it makes sense to force the error.

Thoughts?

**Comment by davecheney** [comment]
@markmandel I cannot reproduce the issue, can you please provide more information.

**Comment by harpreet-sawhney** [comment]
I am seeing this as well. 

gb vendor fetch github.com/Sirupsen/logrus
FATAL command "fetch" failed: github.com/Sirupsen/logrus is already vendored
FATAL command "vendor" failed: exit status 1

The problem seems to happen when I execute "gb vendor fetch" from within **$GB_PROJECT_DIR/src** directory. It works without errors when I execute the same command from within **$GB_PROJECT_DIR**

**Comment by davecheney** [comment]
@harpreet-sawhney that is a different error. Can I ask you to please log a new issue.

**Comment by harpreet-sawhney** [comment]
@davecheney Just edited my previous comment. It was a bad copy-paste on my part. 

To re-iterate

 am seeing this as well.

gb vendor fetch github.com/Sirupsen/logrus
FATAL command "fetch" failed: unable to locate depset for "github.com/Sirupsen/logrus"
FATAL command "vendor" failed: exit status 1

The problem seems to happen when I execute "gb vendor fetch" from within $GB_PROJECT_DIR/src directory. It works without errors when I execute the same command from within $GB_PROJECT_DIR

**Comment by davecheney** [comment]
@harpreet-sawhney thanks for that additional information. I can replicate the problem.

**Comment by davecheney** [comment]
All fixed. Stupid mistake on my part.

**Comment by markmandel** [comment]
:trophy: Thanks! I'll check that out when I get back to work, but I'm sure it's perfect.

Nice find on the sub directory, I didn't realise that was the issue.
