### ISSUE TITLE
gb should support tranisitively building standard library packages

### ISSUE THREAD

**Issue by davecheney** [constabulary/gb#32]
Related to #31 

`gb` currently ignores any package it thinks is part of the standard library; it just assumes they are up to date.

This may not be correct in a cross compilation world, where package resolution and `isStale` calculation could reach all the way back to `runtime`

Can will need to be taken that package resolution always goes, `$GOROOT`, `$PROJECT/src`, $PROJECT/vendor/src` -- it should never be possible for `$PROJECT/src/errors` for example, to override `$GOROOT/src/errors`.

However, when it comes to package compilation time, we want to cache the results of compiling source from `$GOROOT/src` in `$PROJECT/pkg` and this will be tricky.

**Comment by tianon** [comment]
Just ran into this with the innocuous `cmd` name in https://github.com/tianon/go-tags.

`go build` happily spits out a binary, but `gb build` returns the wonderfully cryptic `FATAL command "build" failed: failed to resolve import path "cmd": no buildable Go source files in /usr/lib/go/src/cmd` (because `cmd` exists in `GOROOT`, so it must be `GOROOT/src/cmd` I want to compile, right?  except there are no `.go` files there so it errors out instead :smile:).

**Comment by davecheney** [comment]
@tianon kicking this to a new issue.

**Comment by tianon** [comment]
:heart:!
