### ISSUE TITLE
cmd/gb: gb info should report the build suffix and the package cache directory.

### ISSUE THREAD

**Issue by davecheney** [constabulary/gb#366]
Many tools want to work with the compiled .a files and are confused that gb does not placed them in the same location, relative to the PROJECT/GOPATH that the go tool does. See #202 and #314.

While this is not expected to change in the future, this information should be available for tools that want to integrate with gb projects. 

I propose that gb info grow several more output fields, `GB_PROJECT_PKG_DIR` which will report the path to the project package dir for the current context, taking into account GOOS/GOARCH, cgo status and any build tags, ie `GB_PROJECT_PKG_DIR=/some/path/pkg/linux-arm64-debug`. 

Furthermore while gb always places output binaries in $PROJECT/bin, those binaries may carry a suffix, that suffix should be available in gb info, something like `GB_BIN_SUFFIX=-linux-arm64-nocgo`.

/cc @nsf @fatih

**Comment by nsf** [comment]
Well, I think it's good to have it, at the moment gocode doesn't touch the gb tool itself though. I simply look for $GOOS-$GOARCH in the PROJECT/pkg dir. Which means no support for build flags, but maybe I'll add them one day. It's a hard question, because user needs to tell the gocode that he wants particular build flags. Basically it means there should be an editor with deep Go integration. IDE-like, which allows you to select build tags. If such editor appears and author wants me to add support for that into gocode, I will.
