### ISSUE TITLE
Private Vendor Source

### ISSUE THREAD

**Issue by kmtong** [constabulary/gb#531]
How can we fetch private vendor sources by providing/configuring the username/password, without having to enter the username/password everytime it fetches?

**Comment by davecheney** [comment]
There is currently no mechanism to do this, however vendoring is only done once by the project owner so it should not be a problem. Can you please explain your workflow and I'll see if I can suggest something.

**Comment by stunti** [comment]
I have the same issue so I will chip in. We have several Git repository hosted in Gitlab on one of our server. Some repository are libraries and thus mostly vendored in other project. Since our Gitlab has authentication, every time we do update one of the library we have to refresh the vendor folder. At this time it call for each library's repositories the username/password twice. Which could be 4 or 5 libraries so up to 10 user/password combination.

**Comment by kmtong** [comment]
I am working on the continuous integration server to build the project.  Vendor sources are fetched during build time and so I need some mechanism to specify the credentials.  Locally in my developing machine I SSH key (with GitLab) for the vendor libraries which is fine.

**Comment by stunti** [comment]
@kmtong Bit off topic but how do you vendor with ssh? I thought (I haven't looked at the code yet) it was only https or http.

**Comment by kmtong** [comment]
@stunti I just use GitLab with SSH key as usual.  I suspected that "go get" do the magic.

**Comment by kmtong** [comment]
I found a solution:  https://gist.github.com/shurcooL/6927554
